2025-04-12 11:12:52,543 - WARNING - Task queue depth is 1
2025-04-12 11:12:52,543 - WARNING - Task queue depth is 2
2025-04-12 11:12:53,709 - WARNING - Task queue depth is 1
2025-04-12 11:13:08,181 - WARNING - Task queue depth is 1
2025-04-12 11:16:05,558 - WARNING - Task queue depth is 1
2025-04-12 11:16:05,568 - WARNING - Task queue depth is 1
2025-04-12 11:19:24,853 - WARNING - Task queue depth is 1
2025-04-12 11:19:24,855 - WARNING - Task queue depth is 2
2025-04-12 11:19:24,859 - WARNING - Task queue depth is 1
2025-04-12 11:19:24,865 - WARNING - Task queue depth is 1
2025-04-12 11:20:22,498 - WARNING - Task queue depth is 1
2025-04-12 11:20:22,503 - WARNING - Task queue depth is 2
2025-04-12 11:20:22,504 - WARNING - Task queue depth is 2
2025-04-12 11:20:22,505 - WARNING - Task queue depth is 3
2025-04-12 11:20:22,507 - WARNING - Task queue depth is 4
2025-04-12 11:22:35,682 - ERROR - Exception on /reports [GET]
Traceback (most recent call last):
  File "C:\Project\UI\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\UI\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\UI\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\UI\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\UI\app\routes\catelog.py", line 27, in reports
    return render_template('pages/reports.html',data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\UI\.venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\UI\.venv\Lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\UI\.venv\Lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\UI\.venv\Lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\UI\.venv\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\UI\.venv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\UI\.venv\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: pages/reports.html
2025-04-12 11:23:19,899 - WARNING - Task queue depth is 1
2025-04-12 11:23:19,899 - WARNING - Task queue depth is 2
2025-04-12 11:23:19,901 - WARNING - Task queue depth is 3
2025-04-12 11:23:19,902 - WARNING - Task queue depth is 4
2025-04-12 11:23:19,923 - WARNING - Task queue depth is 2
2025-04-12 11:23:21,680 - WARNING - Task queue depth is 1
2025-04-12 11:23:21,704 - WARNING - Task queue depth is 1
2025-04-12 11:23:21,706 - WARNING - Task queue depth is 2
2025-04-12 11:23:21,707 - WARNING - Task queue depth is 3
2025-04-12 11:23:21,707 - WARNING - Task queue depth is 4
2025-04-12 11:23:21,710 - WARNING - Task queue depth is 5
2025-04-12 11:23:26,440 - WARNING - Task queue depth is 1
2025-04-12 11:23:26,445 - WARNING - Task queue depth is 2
2025-04-12 11:23:26,446 - WARNING - Task queue depth is 3
2025-04-12 11:23:26,448 - WARNING - Task queue depth is 4
2025-04-12 11:23:26,449 - WARNING - Task queue depth is 5
2025-04-12 11:23:27,953 - WARNING - Task queue depth is 1
2025-04-12 11:23:27,960 - WARNING - Task queue depth is 2
2025-04-12 11:23:27,962 - WARNING - Task queue depth is 2
2025-04-12 11:23:27,963 - WARNING - Task queue depth is 3
2025-04-12 11:23:27,971 - WARNING - Task queue depth is 3
2025-04-12 11:23:27,975 - WARNING - Task queue depth is 4
2025-04-12 11:30:21,670 - WARNING - Task queue depth is 1
2025-04-12 11:30:21,682 - WARNING - Task queue depth is 2
2025-04-12 11:30:21,686 - WARNING - Task queue depth is 2
2025-04-12 11:30:21,689 - WARNING - Task queue depth is 3
2025-04-12 11:30:21,692 - WARNING - Task queue depth is 3
2025-04-12 11:30:21,695 - WARNING - Task queue depth is 4
2025-04-12 21:44:58,014 - INFO - Starting Flask app subprocess...
2025-04-12 21:44:58,024 - INFO - 34180
2025-04-12 21:44:58,879 - INFO - Serving on http://127.0.0.1:5000
2025-04-12 21:45:19,336 - WARNING - Task queue depth is 1
2025-04-12 21:45:19,340 - WARNING - Task queue depth is 2
2025-04-12 21:45:19,581 - WARNING - Task queue depth is 2
2025-04-12 21:45:22,730 - WARNING - Task queue depth is 1
2025-04-12 22:02:46,824 - WARNING - Task queue depth is 1
2025-04-12 22:02:46,831 - WARNING - Task queue depth is 1
2025-04-12 22:02:46,833 - WARNING - Task queue depth is 1
2025-04-12 22:02:58,542 - WARNING - Task queue depth is 1
2025-04-12 22:03:01,659 - WARNING - Task queue depth is 1
2025-04-12 22:03:01,663 - WARNING - Task queue depth is 1
2025-04-12 22:03:01,669 - WARNING - Task queue depth is 2
2025-04-23 15:01:37,496 - INFO - Starting Flask app subprocess...
2025-04-23 15:01:37,501 - INFO - 38428
2025-04-23 15:01:37,586 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:01:37,586 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:01:40,586 - INFO - Starting Flask app subprocess...
2025-04-23 15:01:40,592 - INFO - 34000
2025-04-23 15:01:40,696 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:01:40,696 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:01:43,696 - INFO - Starting Flask app subprocess...
2025-04-23 15:01:43,701 - INFO - 33580
2025-04-23 15:01:43,796 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:01:43,796 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:01:46,796 - INFO - Starting Flask app subprocess...
2025-04-23 15:01:46,798 - INFO - 22784
2025-04-23 15:01:46,876 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:01:46,877 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:01:49,877 - INFO - Starting Flask app subprocess...
2025-04-23 15:01:49,885 - INFO - 26232
2025-04-23 15:01:49,981 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:01:49,981 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:01:52,982 - INFO - Starting Flask app subprocess...
2025-04-23 15:01:52,990 - INFO - 32508
2025-04-23 15:01:53,090 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:01:53,090 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:01:56,093 - INFO - Starting Flask app subprocess...
2025-04-23 15:01:56,102 - INFO - 37564
2025-04-23 15:01:56,238 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:01:56,238 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:01:59,240 - INFO - Starting Flask app subprocess...
2025-04-23 15:01:59,242 - INFO - 10964
2025-04-23 15:01:59,325 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:01:59,325 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:02:02,325 - INFO - Starting Flask app subprocess...
2025-04-23 15:02:02,330 - INFO - 13524
2025-04-23 15:02:02,435 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:02:02,435 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:02:05,435 - INFO - Starting Flask app subprocess...
2025-04-23 15:02:05,438 - INFO - 30656
2025-04-23 15:02:05,520 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:02:05,520 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:02:08,520 - INFO - Starting Flask app subprocess...
2025-04-23 15:02:08,526 - INFO - 30532
2025-04-23 15:02:08,632 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:02:08,632 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:02:11,633 - INFO - Starting Flask app subprocess...
2025-04-23 15:02:11,638 - INFO - 4924
2025-04-23 15:02:11,746 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:02:11,746 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:02:14,747 - INFO - Starting Flask app subprocess...
2025-04-23 15:02:14,749 - INFO - 21616
2025-04-23 15:02:14,832 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:02:14,832 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:02:17,833 - INFO - Starting Flask app subprocess...
2025-04-23 15:02:17,839 - INFO - 6656
2025-04-23 15:02:17,917 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:02:17,917 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:02:20,918 - INFO - Starting Flask app subprocess...
2025-04-23 15:02:20,920 - INFO - 9500
2025-04-23 15:02:20,995 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:02:20,995 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:02:23,995 - INFO - Starting Flask app subprocess...
2025-04-23 15:02:24,001 - INFO - 22240
2025-04-23 15:02:24,107 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:02:24,107 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:02:27,108 - INFO - Starting Flask app subprocess...
2025-04-23 15:02:27,110 - INFO - 27908
2025-04-23 15:02:27,182 - ERROR - Traceback (most recent call last):
  File "C:\Project\UI\run.py", line 55, in <module>
    run_flask_app()
  File "C:\Project\UI\run.py", line 43, in run_flask_app
    from app import create_app
  File "C:\Project\UI\app\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

2025-04-23 15:02:27,182 - WARNING - Flask app crashed. Restarting in 3 seconds...
2025-04-23 15:06:48,618 - INFO - Starting Flask app subprocess...
2025-04-23 15:06:48,624 - INFO - 21204
2025-04-23 15:06:49,399 - INFO - Serving on http://127.0.0.1:5000
2025-04-23 15:06:54,522 - WARNING - Task queue depth is 1
2025-04-23 15:06:54,523 - WARNING - Task queue depth is 2
2025-04-23 15:06:54,936 - WARNING - Task queue depth is 2
2025-04-23 15:06:59,095 - WARNING - Task queue depth is 1
